#!/bin/bash

# Will be executed as user "root".

pluginname=REPLACELBPPLUGINDIR

/usr/bin/logger -s "loxberry-plugin-$pluginname - DAEMON Script from ALSA Tools Plugin"

# pluginname=alsatools

# Adding user loxberry to group audio
adduser loxberry audio

# Change permissions - alsamixer-webui.py +x
if [ ! -x $LBHOMEDIR/data/plugins/$pluginname/amixer-webui/alsamixer-webui.py ]; then 
	/usr/bin/logger -s "loxberry-plugin-$pluginname - Setting alsamixer-webui.py +x permissions"
	chmod +x $LBHOMEDIR/data/plugins/$pluginname/amixer-webui/alsamixer-webui.py
fi

# Kill it first
pkill -f alsamixer-webui.py

. $LBHOMEDIR/libs/bashlib/iniparser.sh

iniparser $LBPCONFIG/$pluginname/alsamixer.cfg "Main"

/usr/bin/logger -s "loxberry-plugin-$pluginname - Config variable enabled: $Mainenabled"
	
# Check if mixer is enabled in config
if [ "$Mainenabled" != "true" ]; then
    # If not enabled, leave.
	/usr/bin/logger -s "enabled not true - Exiting."
	exit;
fi

# If port is empty, set default port
if [ ! -z "$Mainport" ]; then
	Mainport="19579"
fi

# Run the webservice
/usr/bin/logger -s "loxberry-plugin-$pluginname - Starting alsamixer-webui on port $Mainport."
	
cd $LBHOMEDIR/data/plugins/$pluginname/amixer-webui
$LBHOMEDIR/data/plugins/$pluginname/amixer-webui/alsamixer-webui.py $Mainport >/dev/null 2>&1 &

exit 0
